name: "development"

on:
  pull_request:
    types: [ "opened", "synchronize", "ready_for_review" ]
    branches: [ "main" ]

jobs:
  message:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "./"
        with:
          apiToken: "${{ secrets.API_KEY }}"
          roomId: "${{ secrets.ROOM_ID }}"
          userIds: "${{ secrets.USER_ID }}"
          body: "get some milk for me."
